// Copyright (c) 2013 The Sippet Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// All supported headers must be kept in lexicographical order
// of their header names.
//
// Organized as follows:
// X(class_name, compact_form, header_name, enum_name, format)

X(Accept,             0,   Accept,              ACCEPT,               MultipleTypeSubtypeParams)
X(AcceptEncoding,     0,   Accept-Encoding,     ACCEPT_ENCODING,      MultipleTokenParams)
X(AcceptLanguage,     0,   Accept-Language,     ACCEPT_LANGUAGE,      MultipleTokenParams)
X(AlertInfo,          0,   Alert-Info,          ALERT_INFO,           MultipleUriParams)
X(Allow,              0,   Allow,               ALLOW,                MultipleTokens)
X(AuthenticationInfo, 0,   Authentication-Info, AUTHENTICATION_INFO,  OnlyAuthParams)
X(Authorization,      0,   Authorization,       AUTHORIZATION,        SchemeAndAuthParams)
X(CallId,             'i', Call-ID,             CALL_ID,              SingleToken)
X(CallInfo,           0,   Call-Info,           CALL_INFO,            MultipleUriParams)
X(Contact,            'm', Contact,             CONTACT,              StarOrMultipleContactParams)
X(ContentDisposition, 0,   Content-Disposition, CONTENT_DISPOSITION,  SingleTokenParams)
X(ContentEncoding,    'e', Content-Encoding,    CONTENT_ENCODING,     MultipleTokens)
X(ContentLanguage,    0,   Content-Language,    CONTENT_LANGUAGE,     MultipleTokens)
X(ContentLength,      'l', Content-Length,      CONTENT_LENGTH,       SingleInteger)
X(ContentType,        'c', Content-Type,        CONTENT_TYPE,         SingleTypeSubtypeParams)
X(Cseq,               0,   CSeq,                CSEQ,                 Cseq)
X(Date,               0,   Date,                DATE,                 Date)
X(ErrorInfo,          0,   Error-Info,          ERROR_INFO,           MultipleUriParams)
X(Expires,            0,   Expires,             EXPIRES,              SingleInteger)
X(From,               'f', From,                FROM,                 SingleContactParams)
X(InReplyTo,          0,   In-Reply-To,         IN_REPLY_TO,          MultipleTokens)
X(MaxForwards,        0,   Max-Forwards,        MAX_FORWARDS,         SingleInteger)
X(MimeVersion,        0,   Mime-Version,        MIME_VERSION,         MimeVersion)
X(MinExpires,         0,   Min-Expires,         MIN_EXPIRES,          SingleInteger)
X(Organization,       0,   Organization,        ORGANIZATION,         TrimmedUtf8)
X(Priority,           0,   Priority,            PRIORITY,             SingleToken)
X(ProxyAuthenticate,  0,   Proxy-Authenticate,  PROXY_AUTHENTICATE,   SchemeAndAuthParams)
X(ProxyAuthorization, 0,   Proxy-Authorization, PROXY_AUTHORIZATION,  SchemeAndAuthParams)
X(ProxyRequire,       0,   Proxy-Require,       PROXY_REQUIRE,        MultipleTokens)
X(RecordRoute,        0,   Record-Route,        RECORD_ROUTE,         MultipleContactParams)
X(ReplyTo,            0,   Reply-To,            REPLY_TO,             SingleContactParams)
X(Require,            0,   Require,             REQUIRE,              MultipleTokens)
X(RetryAfter,         0,   Retry-After,         RETRY_AFTER,          RetryAfter)
X(Route,              0,   Route,               ROUTE,                MultipleContactParams)
X(Server,             0,   Server,              SERVER,               TrimmedUtf8)
X(Subject,            's', Subject,             SUBJECT,              TrimmedUtf8)
X(Supported,          'k', Supported,           SUPPORTED,            MultipleTokens)
X(Timestamp,          0,   Timestamp,           TIMESTAMP,            Timestamp)
X(To,                 't', To,                  TO,                   SingleContactParams)
X(Unsupported,        0,   Unsupported,         UNSUPPORTED,          MultipleTokens)
X(UserAgent,          0,   User-Agent,          USER_AGENT,           TrimmedUtf8)
X(Via,                'v', Via,                 VIA,                  MultipleVias)
X(Warning,            0,   Warning,             WARNING,              MultipleWarnings)
X(WwwAuthenticate,    0,   WWW-Authenticate,    WWW_AUTHENTICATE,     SchemeAndAuthParams)
