// Copyright (c) 2013 The Sippet Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// All supported response codes must be kept in their code order.
//
// Organized as follows:
// X(class_name, code, reason_phrase)

X(Trying,                       100, "Trying")
X(Ringing,                      180, "Ringing")
X(CallIsBeingForwarded,         181, "Call Is Being Forwarded")
X(Queued,                       182, "Queued")
X(SessionProgress,              183, "Session Progress")
X(EarlyDialogTerminated,        199, "Early Dialog Terminated")
X(OK,                           200, "OK")
X(Accepted,                     202, "Accepted")
X(NoNotification,               204, "No Notification")
X(MultipleChoices,              300, "Multiple Choices")
X(MovedPermanently,             301, "Moved Permanently")
X(MovedTemporarily,             302, "Moved Temporarily")
X(UseProxy,                     305, "Use Proxy")
X(AlternativeService,           380, "Alternative Service")
X(BadRequest,                   400, "Bad Request")
X(Unauthorized,                 401, "Unauthorized")
X(PaymentRequired,              402, "Payment Required")
X(Forbidden,                    403, "Forbidden")
X(NotFound,                     404, "Not Found")
X(MethodNotAllowed,             405, "Method Not Allowed")
X(NotAcceptable,                406, "Not Acceptable")
X(ProxyAuthenticationRequired,  407, "Proxy Authentication Required")
X(RequestTimeout,               408, "Request Timeout")
X(Gone,                         410, "Gone")
X(ConditionalRequestFailed,     412, "Conditional Request Failed")
X(RequestEntityTooLarge,        413, "Request Entity Too Large")
X(RequestUriTooLong,            414, "Request-URI Too Long")
X(UnsupportedMediaType,         415, "Unsupported Media Type")
X(UnsupportedUriScheme,         416, "Unsupported URI Scheme")
X(UnknownResourcePriority,      417, "Unknown Resource-Priority")
X(BadExtension,                 420, "Bad Extension")
X(ExtensionRequired,            421, "Extension Required")
X(SessionIntervalTooSmall,      422, "Session Interval Too Small")
X(IntervalTooBrief,             423, "Interval Too Brief")
X(BadLocationInformation,       424, "Bad Location Information")
X(UseIdentityHeader,            428, "Use Identity Header")
X(ProvideReferrerIdentity,      429, "Provide Referrer Identity")
X(FlowFailed,                   430, "Flow Failed")
X(AnonymityDisallowed,          433, "Anonymity Disallowed")
X(BadIdentityInfo,              436, "Bad Identity-Info")
X(UnsupportedCertificate,       437, "Unsupported Certificate")
X(InvalidIdentityHeader,        438, "Invalid Identity Header")
X(FirstHopLacksOutboundSupport, 439, "First Hop Lacks Outbound Support")
X(MaxBreadthExceeded,           440, "Max-Breadth Exceeded")
X(BadInfoPackage,               469, "Bad Info Package")
X(ConsentNeeded,                470, "Consent Needed")
X(TemporarilyUnavailable,       480, "Temporarily Unavailable")
X(CallTransactionDoesNotExist,  481, "Call/Transaction Does Not Exist")
X(LoopDetected,                 482, "Loop Detected")
X(TooManyHops,                  483, "Too Many Hops")
X(AddressIncomplete,            484, "Address Incomplete")
X(Ambiguous,                    485, "Ambiguous")
X(BusyHere,                     486, "Busy Here")
X(RequestTerminated,            487, "Request Terminated")
X(NotAcceptableHere,            488, "Not Acceptable Here")
X(BadEvent,                     489, "Bad Event")
X(RequestPending,               491, "Request Pending")
X(Undecipherable,               493, "Undecipherable")
X(SecurityAgreementRequired,    494, "Security Agreement Required")
X(ServerInternalError,          500, "Server Internal Error")
X(NotImplemented,               501, "Not Implemented")
X(BadGateway,                   502, "Bad Gateway")
X(ServiceUnavailable,           503, "Service Unavailable")
X(ServerTimeOut,                504, "Server Time-out")
X(VersionNotSupported,          505, "Version Not Supported")
X(MessageTooLarge,              513, "Message Too Large")
X(PreconditionFailure,          580, "Precondition Failure")
X(BusyEverywhere,               600, "Busy Everywhere")
X(Decline,                      603, "Decline")
X(DoesNotExistAnywhere,         604, "Does Not Exist Anywhere")
X(NotAcceptableGlobal,          606, "Not Acceptable")
